# **Bank Project**

## **Data Preprocessing**

###Import Libraries 

In [ ]:
import numpy as np
import pandas as pd

### Import the Dataset

In [ ]:
dataset = pd.read_csv('bank.csv', delimiter = ";" )
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)

[[30 'unemployed' 'married' ... -1 0 'unknown']
 [33 'services' 'married' ... 339 4 'failure']
 [35 'management' 'single' ... 330 1 'failure']
 ...
 [57 'technician' 'married' ... -1 0 'unknown']
 [28 'blue-collar' 'married' ... 211 3 'other']
 [44 'entrepreneur' 'single' ... 249 7 'other']]


In [ ]:
print(y)

['no' 'no' 'no' ... 'no' 'no' 'no']


### Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 1 339 4]
 [0.0 0.0 0.0 ... 1 330 1]
 ...
 [0.0 0.0 0.0 ... 11 -1 0]
 [0.0 1.0 0.0 ... 4 211 3]
 [0.0 0.0 1.0 ... 2 249 7]]


### Encoding the dependent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 ... 0 0 0]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 6 -1 0]
 [1.0 0.0 0.0 ... 2 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 3 -1 0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 8 342 9]
 [0.0 1.0 0.0 ... 2 -1 0]]


In [ ]:
print(y_train)

[0 0 0 ... 1 0 0]


In [ ]:
print(y_test)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

In [ ]:
print(x_test)

## **Training the Logistic Regression model on the training set**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## **Pedicting the test result bold text**

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## **Making the Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[763  27]
 [ 73  42]]


0.8895027624309392