# **Bank Project**

# **Data Preprocessing**

###Import Libraries 

In [15]:
import numpy as np
import pandas as pd

### Import the Dataset

In [16]:
dataset = pd.read_csv('bank.csv', delimiter = ";" )
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [17]:
print(x)

[[30 'unemployed' 'married' ... -1 0 'unknown']
 [33 'services' 'married' ... 339 4 'failure']
 [35 'management' 'single' ... 330 1 'failure']
 ...
 [57 'technician' 'married' ... -1 0 'unknown']
 [28 'blue-collar' 'married' ... 211 3 'other']
 [44 'entrepreneur' 'single' ... 249 7 'other']]


In [18]:
print(y)

['no' 'no' 'no' ... 'no' 'no' 'no']


### Encoding categorical data

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 1 339 4]
 [0.0 0.0 0.0 ... 1 330 1]
 ...
 [0.0 0.0 0.0 ... 11 -1 0]
 [0.0 1.0 0.0 ... 4 211 3]
 [0.0 0.0 1.0 ... 2 249 7]]


### Encoding the dependent variable

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[0 0 0 ... 0 0 0]


### Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [23]:
print(x_train)

[[0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 6 -1 0]
 [1.0 0.0 0.0 ... 2 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 3 -1 0]]


In [24]:
print(x_test)

[[1.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 [0.0 1.0 0.0 ... 1 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 1.0 0.0 ... 8 342 9]
 [0.0 1.0 0.0 ... 2 -1 0]]


In [25]:
print(y_train)

[0 0 0 ... 1 0 0]


In [ ]:
print(y_test)